### ISSUE TITLE
On text confirm page, pressing enter is unresponsive

### ISSUE THREAD

**Issue by surdaft** [robherley/snips.sh#104]
### What happened? What is expected?

On confirm text input you are asked on step 1 to say 'y/n' or 'insert new name' however once done it will show 'success!' with the input of 'enter' to submit and 'esc' to go back.. enter does nothing though.

```
snips.sh ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱ u:UZZieyO3Q5 
                                                                                       
file "test" extension set to "plaintext"                                               
                                                                                       
? help • esc go back • enter submit   
```

### How can we reproduce it?

Change extension

**Comment by robherley** [comment]
Fixed in #106
