### ISSUE TITLE
Landing page jitter on mobile view

### ISSUE THREAD

**Issue by SrRyan** [robherley/snips.sh#23]
When scrolling the homepage on a mobile device I have noticed that there is a jitter that happens as the page tries to show the back to `top` arrow on the header of the file. 

https://github.com/robherley/snips.sh/assets/24482028/2af2c660-a970-481d-9b5e-aff3c2dc20d2

**Comment by robherley** [comment]
will look into it 🫡

the js scroll logic is kinda jank, maybe a better idea to use an [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
