### ISSUE TITLE
Compress file content with `zstd`

### ISSUE THREAD

**Issue by robherley** [robherley/snips.sh#6]
https://github.com/facebook/zstd
https://github.com/klauspost/compress has it for go

**Comment by kshuta** [comment]
Hi Rob,

I was thinking of encoding the contents in the  `Upload()` in `internal/ssh/handler.go`, and decoding the contents in `DownloadFile()` in `internal/ssh/handler.go` and `FileHandler()` in `internal/http/handler.go`.

I had two questions before working on the task:

- We now have two files sizes, the file size for the compressed file and the file size for the uncompressed file. Which should we consider when limiting the file size when uploading?
- Should we use stream encoding or block encoding? I don't have knowledge on which is better, but the [doc](https://github.com/klauspost/compress/tree/master/zstd#compressor) says block encodes should be used for small encodes.

**Comment by robherley** [comment]
Instead of doing the encoding/decoding in the handlers directly, I was thinking about making the file's [`Content`](https://github.com/robherley/snips.sh/blob/f31124b37f3daa354af967e5385f0e03a09c05c2/internal/snips/file.go#L23) private, then having setters/getters to control the inflate/deflate. We access the content in a few places (tui, frontend renderer) so having something on the `snips.File` itself probably makes the most sense.

We can use the default compression ratio (3) and I think block encoding is perfectly fine for now, since we read the entire snippet into memory before writing.

As for the upload limit, I think we can still go with the uncompressed size, and we'll persist that uncompressed size in the database too. Less confusing for the end user.

The important thing here is we want to prevent breaking any other snips installations and we can dynamically inflate depending on some the file's content. Like mentioned before, a getter like `GetContent()` method can peek at the file's first four bytes for [zstd magic headers](https://github.com/facebook/zstd/blob/dev/doc/zstd_compression_format.md#zstandard-frames) that are at the start of a frame. We can make something like a `(*File).IsCompressed()` method, so it's compatible with compressed and non-compressed content.

**Comment by robherley** [comment]
Added in https://github.com/robherley/snips.sh/pull/46 🎉 

Thanks @kshuta!
